title: Matuta Edu
description: MATUTA - EXPANSÃO, AUTORIA DE SI E JUVENTUDE
sitename: Matuta
baseurl: '/site'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
